/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2poe;

import conf.conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import conf.conexion;
import conf.Equipo;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andyg
 */
public class JIFrm_Equipo extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFrm_Equipo
     */
    conexion con1 = new conexion();
    Connection conet;
    DefaultTableModel modeloEquipo;
    DefaultTableModel porEquipo;

    static Statement st;
    static ResultSet rs;
    int idc;

    public JIFrm_Equipo() {
        initComponents();
        consultarEquipo();
        Equipo eeq = new Equipo();
        DefaultComboBoxModel modeloEquipo = new DefaultComboBoxModel(eeq.mostrarEquipo());
        jComboBox1.setModel(modeloEquipo);
    }

    void consultarEquipo() {
        String sql = "SELECT * FROM equipo";
        try {
            conet = con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            Object[] equipo = new Object[2];
            modeloEquipo = (DefaultTableModel) jTable_EQUIPO.getModel();
            while (rs.next()) {
                equipo[0] = rs.getInt("id_equipo");
                equipo[1] = rs.getString("nombre_equipo");

                modeloEquipo.addRow(equipo);
            }
            jTable_EQUIPO.setModel(modeloEquipo);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_EQUIPO = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_AGREGAR = new javax.swing.JButton();
        jButton_MODIFICAR = new javax.swing.JButton();
        jButton_ELIMINAR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_NOMBRE = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_JE = new javax.swing.JTable();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_EQUIPO.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jTable_EQUIPO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID EQUIPO", "NOMBRE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_EQUIPO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_EQUIPOMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_EQUIPO);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 770, 252));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setText("OPERACIONES");

        jButton_AGREGAR.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jButton_AGREGAR.setText("AGREGAR  REGISTRO");
        jButton_AGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AGREGARActionPerformed(evt);
            }
        });

        jButton_MODIFICAR.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jButton_MODIFICAR.setText("ACTUALIZAR REGISTRO");
        jButton_MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MODIFICARActionPerformed(evt);
            }
        });

        jButton_ELIMINAR.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jButton_ELIMINAR.setText("ELIMINAR REGISTRO");
        jButton_ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ELIMINARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_MODIFICAR)
                            .addComponent(jButton_AGREGAR, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButton_ELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_AGREGAR, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_MODIFICAR, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_ELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 280, 240));

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel2.setText("DATOS DE LOS EQUIPOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel3.setText("NOMBRE DEL EQUIPO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        jTextField_NOMBRE.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        getContentPane().add(jTextField_NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 190, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel5.setText("ID ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        jTextField_ID.setEditable(false);
        jTextField_ID.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jTextField_ID.setEnabled(false);
        getContentPane().add(jTextField_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 60, -1));

        jComboBox1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 450, -1));

        jTable_JE.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jTable_JE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable_JE);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AGREGARActionPerformed
        // TODO add your handling code here:
        Agregar();
        consultarEquipo();
        jTextField_ID.setText("");
        jTextField_NOMBRE.setText("");
    }//GEN-LAST:event_jButton_AGREGARActionPerformed

    private void jButton_ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ELIMINARActionPerformed
        // TODO add your handling code here:
        Eliminar();
        consultarEquipo();
        jTextField_ID.setText("");
        jTextField_NOMBRE.setText("");
    }//GEN-LAST:event_jButton_ELIMINARActionPerformed

    private void jTable_EQUIPOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_EQUIPOMouseClicked
        // TODO add your handling code here:
        int fila = jTable_EQUIPO.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No se selecciono fila");
        } else {
            idc = Integer.parseInt((String) jTable_EQUIPO.getValueAt(fila, 0).toString());
            String nombre = (String) jTable_EQUIPO.getValueAt(fila, 1);

            jTextField_ID.setText("" + idc);
            jTextField_NOMBRE.setText(nombre);

        }
    }//GEN-LAST:event_jTable_EQUIPOMouseClicked

    private void jButton_MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MODIFICARActionPerformed
        // TODO add your handling code here:
        Modificar();
        consultarEquipo();
        jTextField_ID.setText("");
        jTextField_NOMBRE.setText("");
    }//GEN-LAST:event_jButton_MODIFICARActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Equipo equ = (Equipo) jComboBox1.getSelectedItem();
            try {
                DefaultTableModel modelo = new DefaultTableModel();
                jTable_JE.setModel(modelo);

                PreparedStatement ps = null;
                ResultSet rs = null;
                conexion conn = new conexion();
                java.sql.Connection con = conn.getConnection();

                String sql = "SELECT dui, nombre_completo FROM jugador WHERE id_equipo=" + equ.getId_equipo();
        
                ps = con.prepareStatement(sql);
                rs = ps.executeQuery();

                ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
                int cantidadColumnas = rsMd.getColumnCount();

                modelo.addColumn("DUI JUGADOR");
                modelo.addColumn("NOMBRE JUGADOR");
//                modelo.addColumn("POSICION");
//                 modelo.addColumn("UNIVERSIDAD");
                int[] anchos = {50, 200};
                for (int i = 0; i < jTable_JE.getColumnCount(); i++) {
                    jTable_JE.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
                }

                while (rs.next()) {
                    Object[] filas = new Object[cantidadColumnas];
                    for (int i = 0; i < cantidadColumnas; i++) {
                        filas[i] = rs.getObject(i + 1);
                    }
                    modelo.addRow(filas);
                }
            } catch (SQLException ex) {
                System.err.println(ex.toString());
            }
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    void Agregar() {

        String nombre = jTextField_NOMBRE.getText().toUpperCase();

        try {
            if (nombre.equals("")) {
                JOptionPane.showMessageDialog(null, "Faltan ingresar datos");
                limpiarTabla();
            } else {
                String sql = "insert into equipo(nombre_equipo) values('" + nombre + "')";
                conet = con1.getConnection();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Datos ingresados");
                limpiarTabla();
                limpiarcomboX();

            }
        } catch (Exception e) {
        }
    }

    void limpiarTabla() {
        for (int i = 0; i <= jTable_EQUIPO.getRowCount(); i++) {
            modeloEquipo.removeRow(i);
            i = i - 1;
        }
    }

    void limpiarcomboX() {
        for (int i = 0; i <= jComboBox1.getItemCount(); i++) {
            i = i - 1;
        }
    }

    void Eliminar() {
        int fila = jTable_EQUIPO.getSelectedRow();
        try {
            if (fila < 0) {
                JOptionPane.showMessageDialog(null, "Registro no seleccionado");
                limpiarTabla();
            } else {
                String sql = "delete from equipo where id_equipo=" + idc;
                conet = con1.getConnection();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Registro Eliminado");
                limpiarTabla();
            }
        } catch (Exception e) {
        }
    }

    void Modificar() {
        String nombre = jTextField_NOMBRE.getText().toUpperCase();

        try {
            if (nombre.equals("")) {
                JOptionPane.showMessageDialog(null, "Faltan ingresar datos");
                limpiarTabla();
            } else {

                String sql = "Update equipo set nombre_equipo='" + nombre + "' where id_equipo=" + idc;
                conet = con1.getConnection();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Datos Actualizados");
                limpiarTabla();

            }
        } catch (Exception e) {
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AGREGAR;
    private javax.swing.JButton jButton_ELIMINAR;
    private javax.swing.JButton jButton_MODIFICAR;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_EQUIPO;
    private javax.swing.JTable jTable_JE;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_NOMBRE;
    // End of variables declaration//GEN-END:variables
}
