/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2poe;

import conf.conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andyg
 */
public class JIFrm_Jugadores extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFrm_Jugadores
     */
    conexion con1 = new conexion();
    Connection conet;
    DefaultTableModel modeloj;
    DefaultTableModel modelouni;
    DefaultTableModel equipo;
    DefaultTableModel posicion;
    Statement st;
    ResultSet rs;
    int idc;

    public JIFrm_Jugadores() {
        initComponents();
        consultarJugador();
        uni();
        equipo();
        Posicion();

    }

    void consultarJugador() {
        String sql = "SELECT * FROM jugador";
        try {
            conet = con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            Object[] jugador = new Object[8];
            modeloj = (DefaultTableModel) jTable1.getModel();
            while (rs.next()) {
                jugador[0] = rs.getInt("dui");
                jugador[1] = rs.getString("nombre_completo");
                jugador[2] = rs.getString("edad");
                jugador[3] = rs.getString("estatura_mtrs");
                jugador[4] = rs.getString("peso_lbs");
                jugador[5] = rs.getString("id_posicion");
                jugador[6] = rs.getString("id_universidad");
                jugador[7] = rs.getString("id_equipo");

                modeloj.addRow(jugador);
            }
            jTable1.setModel(modeloj);
        } catch (Exception e) {
        }
    }

    void uni() {
        String sql = "SELECT id_universidad,nombre_uni FROM universidad;";
        try {
            conet = con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            Object[] uni = new Object[2];
            modelouni = (DefaultTableModel) jTable3.getModel();
            while (rs.next()) {
                uni[0] = rs.getInt("id_universidad");
                uni[1] = rs.getString("nombre_uni");

                modelouni.addRow(uni);
            }
            jTable3.setModel(modelouni);
        } catch (Exception e) {
        }
    }

    void equipo() {
        String sql = "SELECT * FROM equipo;";
        try {
            conet = con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            Object[] uni = new Object[2];
            equipo = (DefaultTableModel) jTable4.getModel();
            while (rs.next()) {
                uni[0] = rs.getInt("id_equipo");
                uni[1] = rs.getString("nombre_equipo");

                equipo.addRow(uni);
            }
            jTable4.setModel(equipo);
        } catch (Exception e) {
        }
    }

    void Posicion() {
        String sql = "SELECT * FROM posiciones;";
        try {
            conet = con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            Object[] po = new Object[2];
            posicion = (DefaultTableModel) jTable_Pos.getModel();
            while (rs.next()) {
                po[0] = rs.getInt("id_posicion");
                po[1] = rs.getString("nom_posicion");

                posicion.addRow(po);
            }
            jTable_Pos.setModel(posicion);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton_ACTUALIZAR = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNOMBRE = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        txtDUI = new javax.swing.JFormattedTextField();
        txtxESTATURA = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPESO = new javax.swing.JFormattedTextField();
        txt_ID_posicion = new javax.swing.JTextField();
        txt_edad = new javax.swing.JTextField();
        txt_ID_uni = new javax.swing.JTextField();
        txt_ID_equipo = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable_Pos = new javax.swing.JTable();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DUI", "NOMBRE", "EDAD", "ESTATURA (Mtrs)", "PESO (Lbs)", "ID POSICION", "ID UNIVERSIDAD", "ID EQUIPO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 1210, 330));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jButton1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jButton1.setText("AGREGAR REGISTRO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton_ACTUALIZAR.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jButton_ACTUALIZAR.setText("ACTUALIZAR REGISTRO");
        jButton_ACTUALIZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ACTUALIZARActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jButton3.setText("ELIMINAR REGISTRO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel2.setText("OPERACIONES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_ACTUALIZAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(110, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(79, 79, 79)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_ACTUALIZAR, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel2)
                    .addContainerGap(256, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 60, -1, 290));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel3.setText("DATOS DE LOS JUGADORES");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setText("DUI:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel4.setText("NOMBRE:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        txtNOMBRE.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        getContentPane().add(txtNOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 269, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel5.setText("EDAD:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel6.setText("ESTATURA:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel7.setText("POSICION:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel8.setText("PESO:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel9.setText("ID UNIVERSIDAD:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel10.setText("ID EQUIPO:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, -1, -1));

        jTable3.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID UNIVERSIDAD", "NOMBRE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 240, 110));

        jTable4.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID EQUIPO", "NOMBRE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 270, 110));

        txtDUI.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtDUI.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        txtDUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDUIActionPerformed(evt);
            }
        });
        getContentPane().add(txtDUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 170, 30));

        txtxESTATURA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtxESTATURA.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        txtxESTATURA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtxESTATURAActionPerformed(evt);
            }
        });
        getContentPane().add(txtxESTATURA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 90, -1));

        jLabel11.setText("INGRESA LOS DATOS DEL JUGADOR");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jLabel12.setText("SELECCIONE EL ID DE LA  POSICION, UNIVERSIDAD Y EQUIPO AL QUE PERTENECE");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        txtPESO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtPESO.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        getContentPane().add(txtPESO, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 90, -1));

        txt_ID_posicion.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        txt_ID_posicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ID_posicionActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ID_posicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 50, 30));

        txt_edad.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        getContentPane().add(txt_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 110, 30));

        txt_ID_uni.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        getContentPane().add(txt_ID_uni, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 50, -1));

        txt_ID_equipo.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        txt_ID_equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ID_equipoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ID_equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 50, -1));

        jTable_Pos.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jTable_Pos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID POSICION", "NOMBRE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable_Pos);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 220, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDUIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDUIActionPerformed

    private void txtxESTATURAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtxESTATURAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtxESTATURAActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Agregar();
        consultarJugador();
        txtDUI.setText("");
        txtNOMBRE.setText("");
        txt_edad.setText("");
        txtxESTATURA.setText("");
        txtPESO.setText("");
        txt_ID_posicion.setText("");
        txt_ID_uni.setText("");
        txt_ID_equipo.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Eliminar();
        consultarJugador();
        txtDUI.setText("");
        txtNOMBRE.setText("");
        txt_edad.setText("");
        txtxESTATURA.setText("");
        txtPESO.setText("");
        txt_ID_posicion.setText("");
        txt_ID_uni.setText("");
        txt_ID_equipo.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No se selecciono fila");
        } else {
            idc = Integer.parseInt((String) jTable1.getValueAt(fila, 0).toString());
            String nomb = (String) jTable1.getValueAt(fila, 1);
            String edad = (String) jTable1.getValueAt(fila, 2);
            String estatura = (String) jTable1.getValueAt(fila, 3);
            String peso = (String) jTable1.getValueAt(fila, 4);
            String posicion = (String) jTable1.getValueAt(fila, 5);
            String universidad = (String) jTable1.getValueAt(fila, 6);
            String equipo = (String) jTable1.getValueAt(fila, 7);

            txtDUI.setText("" + idc);
            txtNOMBRE.setText(nomb);
            txt_edad.setText(edad);
            txtxESTATURA.setText(estatura);
            txtPESO.setText(peso);
            txt_ID_posicion.setText(posicion);
            txt_ID_uni.setText(universidad);
            txt_ID_equipo.setText(equipo);
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_ACTUALIZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ACTUALIZARActionPerformed
        // TODO add your handling code here:
        Modificar();
        consultarJugador();
        txtDUI.setText("");
        txtNOMBRE.setText("");
        txt_edad.setText("");
        txtxESTATURA.setText("");
        txtPESO.setText("");
        txt_ID_posicion.setText("");
        txt_ID_uni.setText("");
        txt_ID_equipo.setText("");
    }//GEN-LAST:event_jButton_ACTUALIZARActionPerformed

    private void txt_ID_equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ID_equipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ID_equipoActionPerformed

    private void txt_ID_posicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ID_posicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ID_posicionActionPerformed

    void Modificar() {
        String dui_id = txtDUI.getText().toUpperCase();
        String nomb = txtNOMBRE.getText().toUpperCase();
        String edad = txt_edad.getText().toUpperCase();
        String estatura = txtxESTATURA.getText();
        String peso = txtPESO.getText().toUpperCase();
        String posiciom = txt_ID_posicion.getText().toUpperCase();
        String universidad = txt_ID_uni.getText().toUpperCase();
        String equipo = txt_ID_equipo.getText().toUpperCase();

        try {
            if (dui_id.equals("") || nomb.equals("") || edad.equals("") || estatura.equals("") || peso.equals("") || posiciom.equals("") || universidad.equals("") || equipo.equals("")) {
                JOptionPane.showMessageDialog(null, "Faltan ingresar datos");
                limpiarTabla();
            } else {
//                String sql = "insert into jugador(dui, nombre_completo, edad, estatura_mtrs, peso_lbs,id_posicion, id_universidad,id_equipo ) values(" + dui_id + ",'" + nomb + "','" + edad + "','" + estatura + "','" + peso + "','" + posiciom + "','" + universidad + "','" + equipo + "')";

                String sql = "Update jugador set dui=" + dui_id + ",nombre_completo='" + nomb + "', edad ='" + edad + "',estatura_mtrs='" + estatura + "',peso_lbs='" + peso + "',id_posicion='" + posiciom + "',id_universidad='" + universidad + "',id_equipo='" + equipo + "' where dui=" + idc;
                conet = con1.getConnection();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Datos Actualizados");
                limpiarTabla();
            }
        } catch (Exception e) {
        }
    }

    void Eliminar() {
        int fila = jTable1.getSelectedRow();
        try {
            if (fila < 0) {
                JOptionPane.showMessageDialog(null, "Registro no seleccionado");
                limpiarTabla();
            } else {
                String sql = "delete from jugador where dui=" + idc;
                conet = con1.getConnection();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Registro Eliminado");
                limpiarTabla();
            }
        } catch (Exception e) {
        }
    }

    void Agregar() {
        String dui_id = txtDUI.getText().toUpperCase();
        String nomb = txtNOMBRE.getText().toUpperCase();
//        String edad = jSpinnerEDAD.getValue().toString();
        String edad = txt_edad.getText().toUpperCase();
        String estatura = txtxESTATURA.getText();
        String peso = txtPESO.getText().toUpperCase();
//        String posiciom = jSpinner_POSICION.getValue().toString();
        String posiciom = txt_ID_posicion.getText().toUpperCase();
        String universidad = txt_ID_uni.getText().toUpperCase();
        String equipo = txt_ID_equipo.getText().toUpperCase();
//        String universidad = jSpinner_UNI.getValue().toString();
//        String equipo = jSpinner_EQUIPO.getValue().toString();
        try {
            if (dui_id.equals("") || nomb.equals("") || edad.equals("") || estatura.equals("") || peso.equals("") || posiciom.equals("") || universidad.equals("") || equipo.equals("")) {
                JOptionPane.showMessageDialog(null, "Faltan ingresar datos");
                limpiarTabla();
            } else if (dui_id == dui_id) {
                JOptionPane.showMessageDialog(null, " NO SE PUEDE AGREGAR CON EL MISMO DUI");
                limpiarTabla();

            } else  {
                String sql = "insert into jugador(dui, nombre_completo, edad, estatura_mtrs, peso_lbs,id_posicion, id_universidad,id_equipo ) values(" + dui_id + ",'" + nomb + "','" + edad + "','" + estatura + "','" + peso + "','" + posiciom + "','" + universidad + "','" + equipo + "')";
                conet = con1.getConnection();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Datos ingresados");
                limpiarTabla();
            }
            {

            }
        } catch (Exception e) {
        }
    }

    void limpiarTabla() {
        for (int i = 0; i <= jTable1.getRowCount(); i++) {
            modeloj.removeRow(i);
            i = i - 1;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_ACTUALIZAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable_Pos;
    private javax.swing.JFormattedTextField txtDUI;
    private javax.swing.JTextField txtNOMBRE;
    private javax.swing.JFormattedTextField txtPESO;
    private javax.swing.JTextField txt_ID_equipo;
    private javax.swing.JTextField txt_ID_posicion;
    private javax.swing.JTextField txt_ID_uni;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JFormattedTextField txtxESTATURA;
    // End of variables declaration//GEN-END:variables
}
